plugins {
    id "com.android.application"
}

android {
    namespace "com.anton.clicker"
    compileSdk 35

    defaultConfig {
        applicationId "com.anton.clicker"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // Подписываем debug-ключом, чтобы APK сразу ставился на телефон
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
